### ISSUE TITLE
Stop Web Dev spammers

### ISSUE THREAD

**Issue by johnkahn** [acmutd/acmutd.github.io#19]
We keep getting emails on our contact form about web developers wanting to be hired and change our website. We should put something there saying we are not interested to remove some of this spam from them.

**Comment by izuchukwu** [comment]
I've been observing the spam for quite a while, and it's, without a doubt, automated. A message wouldn't help much.

Need to change contact form services to one that filters spam, or, at minimum, switch to a Typeform embedded form in the meantime (Typeform can send emails for each submission, and wouldn't be hit with spam), which is what we used before the current form service. 

Izuchukwu

**Comment by johnkahn** [comment]
Alright. That sounds better
