### ISSUE TITLE
Scholarship Page Content

### ISSUE THREAD

**Issue by jafrilli** [acmutd/acmutd.github.io#36]
Scholarship page currently empty. Scholarship page need info or scholarship feel useless and unneeded :(. 
Scholarship page need text for the following fields:
- General summary
- "How do I apply for the scholarship?"
- "Who is this scholarship for?"
- "What are the deadlines?"

**Comment by harshasrikara** [comment]
@sid-devic can you help @jafrilli with the necessary information required here?

**Comment by sid-devic** [comment]
We started the "Dr. Gopal Gupta Undergraduate Scholarship for Computer Science established by ACM 2020" in honor of its namesake: Dr. Gopal Gupta served as the Computer Science (CS) department head at UT Dallas from 2009-2020. During this time, the department grew immensely and is now the 3rd largest CS department in the United States. In addition to fostering a culture of undergraduate academic excellence, Dr. Gupta placed a large importance on the role of student organizations within the department and the Erik Jonsson School of Engineering and Computer Science more broadly. One graded assignment for all incoming freshmen in CS is that they attend an event outside of class where they must talk to representatives from many CS student organizations. Furthermore, Dr. Gupta encouraged students to listen in on department meetings, provide feedback on programs within the department, and present goals and events to faculty members. Finally, Dr. Gupta initiated efforts to start HackUTD, a university hackathon, which has grown to be one of the largest in the U.S. 

Each year, this endowed scholarship will award one student $1k, qualifying it for "competitive scholarship" status. This means that if you are an out of state or international student, you may receive in-state tuition for that year. For this reason, we highly encourage these demographics to apply. In addition to academic excellence, applicants will be preferred if they have demonstrated engagement with any CS student organization at UTD. Note that the scholarship is awarded by a committee appointed by the Jonsson school, and not ACM UTD or Prof. John Cole (our faculty sponsor). Please _do not_ get in touch with us on questions regarding this scholarship.

Instructions, information, help, and deadlines for applying can be found [here](https://engineering.utdallas.edu/engineering/academics/undergraduate-majors/scholarships/)!

**Comment by sid-devic** [comment]
Sorry, I just found out about this question!

**Comment by sid-devic** [comment]
@jafrilli

**Comment by sid-devic** [comment]
bump lmao
