### ISSUE TITLE
Update information for spring 2021 officer changes

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/acmutd.github.io#50]
The [team](https://www.acmutd.co/team.html) page needs to be updated to reflect changes in officers who will leave ACM or join ACM after the spring 2021 semester.

Two new directors have been onboarded for the spring 2021:
- Director of Development
- Director of Research

Additionally, a few teams have taken on new officers:
- HackUTD
- Development

For a list of current officers, see [this spreadsheet](https://docs.google.com/spreadsheets/d/1nLhtCfl5kZXiOUN0tNO9wtnxRo-39KjJA6I4qDW_Kkk/edit#gid=630343822). Anyone whose name is not on the "Current ACM Team" sheet needs to be removed from the team page. Titles for officers also need to be updated, as well.

**Comment by WillieCubed** [comment]
Hey @Stevenmqnguyen, how's this going?

**Comment by stevenmqnguyen** [comment]
Should have a pr by tomorrow's meeting

**Comment by WillieCubed** [comment]
Turns out we missed a few officers. [This document](https://docs.google.com/spreadsheets/d/17qnTKXWCox2yKfc1uDSH0KPv7NAriXhQCmXgTnCmYIs/edit#gid=0) contains a list of officers that should be on the website as of the send of the spring semester. After June 6, go ahead and make another PR to address the changes.

**Comment by stevenmqnguyen** [comment]
Hmm my name isn't on that doc either.

**Comment by NickBurnett** [comment]
Same as Steven, my name isn't there.

**Comment by WillieCubed** [comment]
Should be updated now. If you notice any other abnormalities, feel free to correct them.
