### ISSUE TITLE
Website missing projects officers

### ISSUE THREAD

**Issue by FrancisMasangcay** [acmutd/acmutd.github.io#62]
ACM Website currently only lists 7/9 Projects Officers.

Missing Officers and corresponding LinkedIn url's are:

- Palak Bhargava : https://www.linkedin.com/in/palak-bhargava01/
- Kenneth Antilla : https://www.linkedin.com/in/kennethanttila/

Attached are the headshot images to be displayed on the website. Order of photos is Palak followed by Kenneth

![palak_bhargava](https://user-images.githubusercontent.com/54854060/147768130-7f2fcb7e-d34a-41ef-b819-a31ec84909a1.jpg)
![kenneth_anttila](https://user-images.githubusercontent.com/54854060/147768134-7ff9cb74-8897-4847-bd8d-89ae23b905e6.jpeg)

**Comment by WillieCubed** [comment]
Hmm, this is unexpected. There appears to be a regression since both the officers are present in the [codebase](https://github.com/acmutd/acmutd.github.io/tree/master/_officers) like the other new ones. I'll look into this.

**Comment by WillieCubed** [comment]
There were two missing quotation marks from each of their officer metadata, which caused the GitHub Pages build to ignore them. Pushing changes now.
