### ISSUE TITLE
Add Professor Cole to the Team Page

### ISSUE THREAD

**Issue by sakshamsangraula** [acmutd/acmutd.github.io#68]
Professor Cole mentioned that he is not in the Team Page of our website. Please include him in our Team Page as our Faculty Advisor.

**Comment by WillieCubed** [comment]
Could you provide a photo of the desired headshot?

**Comment by sakshamsangraula** [comment]
> 

I just asked for a photo and will include it here once I receive it. Thanks for the reminder!

**Comment by sakshamsangraula** [comment]
Professor Cole let me know that we can use the photo from his website: https://personal.utdallas.edu/~John.Cole/
so please use this headshot for the team page.
